# Generated by Django 3.2.7 on 2021-09-09 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('lat', models.DecimalField(decimal_places=10, max_digits=10, verbose_name='latitude')),
                ('lng', models.DecimalField(decimal_places=10, max_digits=10, verbose_name='longitude')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('locationmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='covid_data.locationmodel')),
                ('has_state_provinces', models.BooleanField(default=False)),
            ],
            bases=('covid_data.locationmodel',),
        ),
        migrations.CreateModel(
            name='StateProvince',
            fields=[
                ('locationmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='covid_data.locationmodel')),
                ('country_of_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid_data.country')),
            ],
            bases=('covid_data.locationmodel',),
        ),
        migrations.CreateModel(
            name='CovidDatum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('confirmed', models.IntegerField(verbose_name='confirmed')),
                ('deaths', models.IntegerField(verbose_name='deaths')),
                ('recovered', models.IntegerField(verbose_name='recovered')),
                ('active', models.IntegerField(verbose_name='active')),
                ('incident_rate', models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True, verbose_name='incident rate')),
                ('fatality_ratio', models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True, verbose_name='fatality ratio')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='covid_data.country')),
                ('state_province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='covid_data.stateprovince')),
            ],
        ),
    ]
