# Generated by Django 3.2.7 on 2021-09-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coviddatum',
            name='city',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='city'),
        ),
    ]
