# Generated by Django 3.2.7 on 2021-09-09 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid_data', '0002_coviddatum_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationmodel',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='locationmodel',
            old_name='lng',
            new_name='longitude',
        ),
    ]
