# Generated by Django 3.2.7 on 2021-09-12 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_data', '0005_auto_20210912_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coviddatum',
            name='active',
            field=models.IntegerField(default=0, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='coviddatum',
            name='confirmed',
            field=models.IntegerField(default=0, verbose_name='confirmed'),
        ),
        migrations.AlterField(
            model_name='coviddatum',
            name='deaths',
            field=models.IntegerField(default=0, verbose_name='deaths'),
        ),
        migrations.AlterField(
            model_name='coviddatum',
            name='recovered',
            field=models.IntegerField(default=0, verbose_name='recovered'),
        ),
    ]
