# Generated by Django 3.2.7 on 2021-09-12 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_data', '0006_auto_20210912_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coviddatum',
            name='fatality_ratio',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=20, verbose_name='fatality ratio'),
        ),
        migrations.AlterField(
            model_name='coviddatum',
            name='incident_rate',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=20, verbose_name='incident rate'),
        ),
    ]
