# Generated by Django 3.2.7 on 2021-09-13 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid_data', '0007_auto_20210912_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coviddatum',
            old_name='city',
            new_name='city_county',
        ),
    ]
